name: Ansible Lint

on:
  workflow_call:

jobs:
  lint:
    name: Run ansible-lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get repo name
        id: repo_name
        run: |
          repo_name=$(basename "$GITHUB_REPOSITORY")
          echo "REPO_NAME=$repo_name" >> $GITHUB_OUTPUT

      - name: Copy repository into directory with repo name
        run: |
          mkdir "${{ steps.repo_name.outputs.REPO_NAME }}"
          shopt -s extglob  # Needed to copy hidden files
          # Copy everything except the parent directory
          cp -r !("${{ steps.repo_name.outputs.REPO_NAME }}") "${{ steps.repo_name.outputs.REPO_NAME }}"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install ansible and ansible-lint
        run: |
          pip install ansible ansible-lint

      - name: Run ansible-lint
        run: |
          ansible-lint ${{ steps.repo_name.outputs.REPO_NAME }}
