name: Auto Tag Creation on Main Push

on:
  push:
    branches:
      - main

permissions:
  contents: write  # needed to push the new tag

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # important to get all tags

      - name: Get latest tag
        id: get_tag
        run: |
          # Get latest tag (v* format) or default to v1.0.0
          TAG=$(git tag --sort=-v:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)
          echo "Latest tag: $TAG"

          if [[ -z "$TAG" ]]; then
            TAG="v1.0.0"
          fi

          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Bump patch version
        id: bump_tag
        run: |
          TAG=${{ steps.get_tag.outputs.tag }}
          echo "Current tag: $TAG"

          VERSION=${TAG#v}
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          NEW_TAG="v$MAJOR.$MINOR.$((PATCH + 1))"

          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT

      - name: Create new tag and push
        run: |
          NEW_TAG=${{ steps.bump_tag.outputs.new_tag }}
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag "$NEW_TAG"
          git push origin "$NEW_TAG"
