name: Auto Tag Creation on Main Push

on:
  push:
    branches:
      - main

permissions:
  contents: write  # needed to push the new tag

jobs:
  auto-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed to fetch tags and full history

      - name: Get latest tag
        id: get_tag
        run: |
          TAG=$(git tag --sort=-v:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)
          echo "Latest tag: $TAG"

          if [[ -z "$TAG" ]]; then
            TAG="v1.0.0"
          fi

          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Bump patch version
        id: bump_tag
        run: |
          TAG=${{ steps.get_tag.outputs.tag }}
          VERSION=${TAG#v}
          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          NEW_TAG="v$MAJOR.$MINOR.$((PATCH + 1))"

          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT

      - name: Get last commit message (PR title)
        id: commit_msg
        run: |
          MSG=$(git log -1 --pretty=%s)
          echo "msg=$MSG" >> $GITHUB_OUTPUT

      - name: Create new tag with PR title
        run: |
          NEW_TAG=${{ steps.bump_tag.outputs.new_tag }}
          MESSAGE=${{ steps.commit_msg.outputs.msg }}

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@lesposito87.noreply.github.com"

          git tag -a "$NEW_TAG" -m "$MESSAGE"
          git push origin "$NEW_TAG"
