name: Build and Push Multi-Arch Docker Image

on:
  workflow_call:
    inputs:
      docker_repo:
        description: "Docker Hub repository (e.g., lesposito87/poorman-aws-playground)"
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU (for ARM64 emulation)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set repository variable
        run: echo "REPO=${{ inputs.docker_repo }}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine tag and build condition
        if: github.event_name != 'pull_request' || github.event.action != 'closed'
        id: determine_tag
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            TAG="pr-${{ github.event.pull_request.number }}"
            echo "TAGS=$REPO:$TAG" >> $GITHUB_ENV
            echo "BUILD_IMAGE=true" >> $GITHUB_ENV

          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            PR_NUMBER=$(git log -1 --pretty=%B | grep -oE '#[0-9]+' | tr -d '#')

            if [[ -n "$PR_NUMBER" ]]; then
              echo "PR_TAG=pr-$PR_NUMBER" >> $GITHUB_ENV
            fi

            LATEST_TAG=$(curl -s "https://hub.docker.com/v2/repositories/$REPO/tags/?page_size=100" | jq -r '.results[] | select(.name | test("^[0-9]+\\.[0-9]+\\.[0-9]+$")) | .name' | sort -V | tail -n 1)
            [[ "$LATEST_TAG" == "null" || -z "$LATEST_TAG" ]] && LATEST_TAG="1.0.0"
            MAJOR=$(echo "$LATEST_TAG" | cut -d. -f1)
            MINOR=$(echo "$LATEST_TAG" | cut -d. -f2)
            PATCH=$(echo "$LATEST_TAG" | cut -d. -f3)
            NEW_TAG="$MAJOR.$MINOR.$((PATCH + 1))"
            echo "TAGS=$REPO:$NEW_TAG,$REPO:latest" >> $GITHUB_ENV
            echo "BUILD_IMAGE=true" >> $GITHUB_ENV

          else
            echo "BUILD_IMAGE=false" >> $GITHUB_ENV
          fi

      - name: Build and push multi-arch image
        if: env.BUILD_IMAGE == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.TAGS }}
          platforms: linux/amd64,linux/arm64

      - name: Remove PR image tag on PR close
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        run: |
          REPO=${{ inputs.docker_repo }}
          TAG="pr-${{ github.event.pull_request.number }}"
          echo "Removing PR image tag $REPO:$TAG from Docker Hub"
          curl -X DELETE "https://hub.docker.com/v2/repositories/$REPO/tags/${TAG}/" \
            -H "Authorization: Bearer ${{ secrets.DOCKERHUB_TOKEN }}"

